query FetchCategories($limit: Int!, $page: Int!, $search: String) {
  categories(limit: $limit, page: $page, search: $search) {
    per_page
    total
    data {
      id
      user_id
      parent_id
      name
      description
      image_src
    }
  }
}
